// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfPszcvnoiJNNT2kmCaNxTpIZNm_-k8E',
    appId: '1:635337142:web:f88b5dc27f8e48cc67e917',
    messagingSenderId: '635337142',
    projectId: 'dharamshala-28df7',
    authDomain: 'dharamshala-28df7.firebaseapp.com',
    storageBucket: 'dharamshala-28df7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCNbVSq9ffS51oJ0LyzS1xWk3Dlm0ub4',
    appId: '1:635337142:android:9d118c27feee431767e917',
    messagingSenderId: '635337142',
    projectId: 'dharamshala-28df7',
    storageBucket: 'dharamshala-28df7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIy40ywBlbXhzzTkqATBqkg4TETDHEY-A',
    appId: '1:635337142:ios:2d01427dc147a6c867e917',
    messagingSenderId: '635337142',
    projectId: 'dharamshala-28df7',
    storageBucket: 'dharamshala-28df7.firebasestorage.app',
    iosBundleId: 'com.example.dharamshalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIy40ywBlbXhzzTkqATBqkg4TETDHEY-A',
    appId: '1:635337142:ios:2d01427dc147a6c867e917',
    messagingSenderId: '635337142',
    projectId: 'dharamshala-28df7',
    storageBucket: 'dharamshala-28df7.firebasestorage.app',
    iosBundleId: 'com.example.dharamshalaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfPszcvnoiJNNT2kmCaNxTpIZNm_-k8E',
    appId: '1:635337142:web:7d4b9c360924036867e917',
    messagingSenderId: '635337142',
    projectId: 'dharamshala-28df7',
    authDomain: 'dharamshala-28df7.firebaseapp.com',
    storageBucket: 'dharamshala-28df7.firebasestorage.app',
  );
}
